version: "3.3"

services:
  go-blog:
    build: ./src
    container_name: go-blog
    ports:
      - 8080:8080
    environment:
      MONGODB_CONNECTTION_URI : mongodb://root:root@mongodb-blog:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      JWT_SECRET : jwtsecret
      JWT_LIFE_TIME : 19
    depends_on:
      - mongodb-blog

  mongodb-blog:
    image: mongo
    container_name: mongodb-blog
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
